name: 'Test action'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    if: ${{ !contains(github.event.pull_request.title, '[cov]') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./emulator
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Build project
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
  
  test-with-coverage:
    if: contains(github.event.pull_request.title, '[cov]')
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    
    defaults:
      run:
        working-directory: ./emulator

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Build project
      run: cargo build --verbose

    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: '0.15.0'
        args: '--out Xml --output-dir resources --no-fail-fast'

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: 'resources/cobertura.xml'
        badge: true
        format: 'markdown'
        output: 'both'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
