name: 'Settings Test Action'

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  actions: read
  checks: write
  contents: read
  pull-requests: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    uses: FairgateLabs/BitVMX-CI/.github/workflows/ci_local_template.yml@main
    with:
      repo: 'FairgateLabs/rust-bitvmx-workspace'
      submodule_path: 'rust-bitvmx-settings'
      cargo_lock_path: 'rust-bitvmx-settings/Cargo.lock'
      target_path: 'rust-bitvmx-settings/target'
      clippy: true
    secrets: inherit
